### PR TITLE
Add support for rocket and eyes reactions.

### PR DESCRIPTION
**Pull request by rdvdijk**
# Description 
Added the missing reactions :rocket: and :eyes:.

# Before submitting a PR:
We love getting PRs, but we hate asking people for the same basic changes every time. 

- [x] Push your changes to a branch other than `master`. Create your PR from that branch.    
- [ ] ~~Add JavaDocs and other comments~~ (already present)
- [ ] ~~Write tests that run and pass in CI. See [CONTRIBUTING.md](CONTRIBUTING.md) for details on how to capture snapshot data.~~ (there are no tests for this enum)
- [ ] ~~Run `mvn -D enable-ci clean install site` locally. This may reformat your code, commit those changes. If this command doesn't succeed, your change will not pass CI.~~ (`master` branch fails on coverage checks)

### CODE REVIEW

**Comment by bitwiseman** [comment]
(I'll fix `master` momentarily.)

**Comment by rdvdijk** [comment]
> Cool! Please add a test.

Will do! Will a unit test verifying the `forContent()` for all `enum` values method suffice?

**Comment by bitwiseman** [comment]
@rdvdijk  
Yes that would be great.

**Comment by bitwiseman** [comment]
@rdvdijk  I got it.  Thanks for the submission!

**Pull request merged**
