### PR TITLE
Add support for projects

### PR DESCRIPTION
**Pull request by martinvanzijl**
Fixes issue #425.

Added methods:

- GitHub.getProject(int id)
- GHRepository.createProject()
- GHRepository.listProjects()
- GHOrganization.createProject()
- GHOrganization.listProjects()

Added the GHProject class.

### CODE REVIEW

**Comment by JosephHobbs** [comment]
I was just looking for a library specifically for interacting with projects in Github!  This is great!

**Comment by geir-origin-no** [comment]
I'm looking for this functionality as well, would be great if it was merged and released!

**Comment by gskjold** [comment]
I also had use for this, so I extended @martinvanzijl contribution with columns and cards. Also added some tests, hoping they are sufficient @bitwiseman .

I'm not used to forks and how to contribute in the correct way here, but that might just be another pullreq? 
Ref: https://github.com/gskjold/github-api/tree/issue_425_projects_columns_cards

**Comment by bitwiseman** [comment]
@gskjold Start a new PR and reference this one so we know to close this.

**Comment by bitwiseman** [comment]
Moving to a new PR.

**Comment by martinvanzijl** [comment]
Thanks, will delete my branch.

**Pull request closed without merging**
