### PR TITLE
Add support for draft pull requests

### PR DESCRIPTION
**Pull request by vbehar**
See https://developer.github.com/v3/pulls/#input
and https://help.github.com/en/articles/about-pull-requests#draft-pull-requests

### CODE REVIEW

**Comment by sullis** [comment]
any update on this PR?   I'd like to start using Draft Pull Requests :)

**Comment by bitwiseman** [comment]
@sullis 
We need tests that show this working in CI.  Could you implement them?

**Comment by vbehar** [comment]
Hi,
sorry for not being more active on this one. I'll try to work on the tests this week.
@sullis if you want to do it, please feel free to do so ;-)

**Comment by vbehar** [comment]
thanks @bitwiseman for finishing this and adding the tests!

**Pull request merged**
