### PR TITLE
Add createTag() method to GHRepository

### LINKED ISSUE #500: Add Create Tags method
I'm still looking over the code, and am not sure if this feature exists or not.  It looks like the process for creating remote tags is a little tricky, but you can [create a tag object](https://developer.github.com/v3/git/tags/#create-a-tag-object) with the underlying JSON api, and then [create a reference to a tag](https://developer.github.com/v3/git/refs/#create-a-reference) to make an annotated tag visible in github.  

It seems this project has a [Tag Object](https://github.com/kohsuke/github-api/blob/master/src/main/java/org/kohsuke/github/GHTagObject.java) but unless I'm mistaken, only read operations are implemented so far?

### PR DESCRIPTION
**Pull request by martinvanzijl**
# Description 
Adds the createTag() method to GHRepository. Fixes #500. 

Possible further enhancements are:

* Add unit tests for tagging a "tree" and "blob".
* Add versions of the method which take `GHCommit`, `GHBlob` or `GHTree` instead of the `object` and `type` parameters.
* Add a version of the method which takes parameters for the tagger (name, email and date). This is optional, though, and seems to default to the user's credentials.
* Add a `GHCommit.createTag()` method.

### CODE REVIEW

**Comment by bitwiseman** [comment]
@martinvanzijl 
Looks like a test failed.  Otherwise this change looks good.

**Comment by martinvanzijl** [comment]
@bitwiseman Thanks, I had trouble getting the clean-up method to work, so I moved the test case to it's own class (GHTagTest). Looks like it's working on my PC. Let's see how it does in the automated CI Build and Test.

**Comment by martinvanzijl** [comment]
Nope, JavaDoc warning...

> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.8.2:site (default-site) on project github-api: Error generating maven-javadoc-plugin:3.1.1:aggregate-no-fork report: Project contains Javadoc Warnings -> [Help 1]

I forgot to run "mvn install site". Let me try that now...

**Comment by martinvanzijl** [comment]
Oh, I see, I have to add a description to the JavaDoc comment...

> [WARNING] /home/runner/work/github-api/github-api/src/main/java/org/kohsuke/github/GHRepository.java:2669: warning: no description for @throws
> [WARNING] * @throws java.io.IOException

Let my try that...

**Comment by martinvanzijl** [comment]
Oops, formatting error:

> [ERROR] Failed to execute goal net.revelc.code.formatter:formatter-maven-plugin:2.11.0:validate (default) on project github-api: File '/home/runner/work/github-api/github-api/src/main/java/org/kohsuke/github/GHRepository.java' has not been previously formatted.  Please format file and commit before running validation! -> [Help 1]

I'll try running "mvn install site" again.

**Comment by martinvanzijl** [comment]
Looks like it's working OK now!

**Pull request merged**
