### PR TITLE
[#690]Implement the ability to read `total_private_repos` for GHPerson

### PR DESCRIPTION
**Pull request by Sage-Pierce**
# Description 
I took a crack at implementing what is mentioned in #690 

For test writing, I wasn't sure whether to add to `GHPersonTest` or `GHUserTest`. Went with `GHUserTest` since that's a resource under which you can create a private repo

# Prerequisites:

- [x] Push your changes to a branch other than `master`. Create your PR from that branch.    
- [x] Add JavaDocs and other comments
- [x] Write tests that run and pass in CI. See [CONTRIBUTING.md](CONTRIBUTING.md) for details on how to capture snapshot data.
- [x] Run `mvn formatter:format`. This may reformat your code, commit those changes. If the command `mvn -D enable-ci install site` locally command doesn't succeed, your change will not pass CI.

### CODE REVIEW

**Comment by Sage-Pierce** [comment]
Some of the CI steps keep failing on:

`File '/home/runner/work/github-api/github-api/src/test/java/org/kohsuke/github/GHUserTest.java' has not been previously formatted.  Please format file and commit before running validation!`

However, I've run `mvn formatter:format` locally and committed the result. The `validate` goal passes locally, but apparently not on CI. Any ideas on why that's the case?

**Comment by bitwiseman** [comment]
@Sage-Pierce  Are you running on windows?

**Comment by Sage-Pierce** [comment]
I'm running on a Mac (High Sierra)

**Comment by bitwiseman** [comment]
Ugh. That was not what I wanted to do. 😞

**Comment by Sage-Pierce** [comment]
Thanks for the (inadvertent) merge 😄 

...And subsequent fix for the formatting. Should the formatting be run differently on a MacBook? Just curious what I needed to do to get the correct formatting

**Comment by bitwiseman** [comment]
I fixed the instructions: you just need to do `mvn clean` to make sure the formatter does all the needed formatting.

**Comment by Sage-Pierce** [comment]
@bitwiseman Gotcha

Could you provide an estimate on when there will be a new release containing this change? 

Thanks!

**Pull request merged**
