### PR TITLE
Convert GHMilestone to updater

### PR DESCRIPTION
**Pull request by bitwiseman**
@martinvanzijl
How about this instead of the `set*` methods?

### CODE REVIEW

**Comment by bitwiseman** [comment]
@PauloMigAlmeida  Any thoughts on this?

**Comment by PauloMigAlmeida** [comment]
@bitwiseman I agree with the approach.

**Comment by martinvanzijl** [comment]
@bitwiseman
My thoughts are: I recommend keeping the original methods un-deprecated, since the builder syntax is cumbersome when updating a single field, e.g.:
`milestone.update().title("New Title").update();`

The syntax also looks strange when closing a milestone, e.g.:
`milestone.update().close();`

Just `milestone.close()` makes more sense to me.

**Comment by bitwiseman** [comment]
@martinvanzijl 
Yeah, I see your point.  
On the other hand, offering (and supporting) both has its own problems.
I'm going to close this for the moment.

**Pull request closed without merging**
